### ISSUE TITLE
Reduce required python version to 3.10

### ISSUE THREAD

**Issue by badrobit** [davidism/gha-update#4]
Not sure if there is something specific from Python 3.12 you are looking for but if you could reduce it to require something less than 3.12 it would make it much easier to use!

**Comment by davidism** [comment]
What makes it difficult to use with 3.12?

**Comment by badrobit** [comment]
> What makes it difficult to use with 3.12?

just that we may not be able to fully deploy 3.12, I wish it was something I could easily deploy just not all companies are there yet. For my personal stuff everything is already 3.12. You might be able to work around it with a `pre-commit hook` as I think they get their own environments but I am not 100% sure about that.

**Comment by davidism** [comment]
You don't need to deploy it, you just need it on your machine where you'll run this command. If pre-commit can already create Python 3.12 envs on your machine, then you already have 3.12. I don't think I want to commit to more expansive maintenance promises at this time.

**Comment by badrobit** [comment]
I think you miss understood, I don't have the ability to use 3.12 on all our work systems. Shame as 3.10 and 3.12 are very similar so pretty sure there wouldn't have been a lot more maintenance. will check back in with the tool if/when we can roll out 3.12
