### ISSUE TITLE
provide a pre-commit hook

### ISSUE THREAD

**Issue by badrobit** [davidism/gha-update#5]
It would be amazing if we could add this as part of our [`pre-commit`](https://pre-commit.com/) tool chain to always ensure our actions are up-to-date before anything is committed to GitHub.

**Comment by davidism** [comment]
This is not something that should run in pre-commit. First, it would make network calls on every commit. Second, the entire premise of the tool is to be something that is run manually (or close to manually), and I don't feel that "run every commit" matches that goal.
